# Generated by Django 5.0.1 on 2024-02-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamitos', '0002_cliente_user_prestamo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='total_pagar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
